#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

yabai -m space 1 --label dev
yabai -m space 2 --label browser
yabai -m space 3 --label music
yabai -m space --focus dev

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Audio MIDI Setup$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^CooperVPNMac$" manage=off

yabai -m config external_bar all:26:0

